#This file is used to seperately define the hyperparameter values to keep a clean code. 
# It is also easier to keep the logs if all this information is one seperate document

model_name: resent18
num_classes: 10

#Training settings
epochs: 10
batch_size: 64
learning_rate: 0.001

#File path
checkpoint_path: checkpoints/resnet18_cifar10.pth
